FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY recommendation/ ./recommendation/
COPY models/ ./models/
COPY data/ ./data/

EXPOSE 8501

CMD ["streamlit", "run", "recommendation/recommendation_app.py", "--server.port=8501", "--server.address=0.0.0.0"]